# TODO replace name with name of ebook: 101: Intro to Web, 411: Front-Ends with React...etc
site_name: Learning with AI

# TODO inside `ebook-folder/`
# TODO run `git clone https://github.com/squidfunk/mkdocs-material.git`
# TODO run `pip install -r requirements.txt` (see inside mkdocs-material/)
# TODO run `mkdocs build` to build the static files into "/site"
# TODO run `mkdocs serve` to serve those files to http://127.0.0.1:8000
# TODO replace all CAPITALIZED words with appropriate titles
# ! Use the files in workspace/resources to quickly generate class and lesson templates, see `cp ...` script at bottom of each file
# ! Use the folder workspace/developmentDocumentation to record thoughts and future improvements

# defines where the markdown to build from
# docs_dir: 'test-node-book'

# defines where to put the generated static files
# site_dir: 'docs'

# "pages" has been deprecated
# use this to create the nav bar on the left-side of the window view
# TODO replace all CAPITALIZED words with appropriate titles

nav:
  - Home: 'index.md'
  - 'Part 1: Intro to AI':
    - 'What & What Not': module-1/whatItIsAndWhatItIsnt.md
    - 'Learn Something': module-1/learnSomethingWithAI.md
    - 'Practice Chatting': module-1/practiceLearningWithAI.md
  - 'Part 2: Learning Strategies':
    - 'Start with a Goal': module-1/startWithAGoal.md
    - 'Break It Down': module-1/breakItDown.md
    - 'Customize': module-1/customizeToYourLearningStyle.md
    - 'Reinforce pt. 1': module-1/mentalRetentionStrategies.md
    - 'Reinforce pt. 2': module-1/mentalRetentionStrategies-2.md
    - 'Accountability': module-1/accountabilityPartner.md
    - 'Keep It Alive': module-1/keepLearningAlive.md
    # - 'Collaboration': module-1/collaborationWithChatGPT.md
  # - 'Part 3: Advanced Techniques':
    # - Advanced Proficiency Techniques: module-1/advancedProficiencyTechniques.md
    # cp workspace/resources/templateFile.md docs/module-
    # cp workspace/resources/classOutlineTemplate.md docs/module-
  - 'Additional Resources':
    # - Develop Series Collection: additionalResources/developSeries.md
    - Interesting Prompts: additionalResources/thoughtProvokingPrompts.md
    - Keyboard Shortcuts: additionalResources/keyboardShortcuts.md
    - Git & CLI Commands: additionalResources/gitCommands.md
    - Learn Your CLI: additionalResources/learnYourCLI.md    
      # - 'Bonus Materials':


# defines the styles, usually just a single name but `custom_dir` overrides this behavior
theme:
  name: material
  # was null
  palette:
    scheme: slate
    primary: black
    accent: deep orange
    # Defines the logo in the top-left, file must be in the /doc directory
  logo: CE_WhiteBlue_Icon.png
  features:
    - navigation.tabs
    - navigation.instant
    - header.autohide

  # ? Not rendering as expected??
  extra:
    copyright: Copyright &copy; 2013 - 2021 Austin Coding Academy
    social:
      - icon: fontawesome/brands/github
        link: https://github.com/AustinCodingAcademy
      - icon: fontawesome/brands/medium
        link: https://medium.com/@austincoding
      - icon: fontawesome/brands/linkedin
        link: https://www.linkedin.com/school/austincodingacademy/
      - icon: fontawesome/brands/instagram
        link: https://www.instagram.com/austincodingacademy
      - icon: fontawesome/brands/twitter
        link: https://twitter.com/austincoding
      - icon: fontawesome/brands/facebook
        link: https://www.facebook.com/AustinCodingAcademy/


  
  # 404 page
  static_templates:
    - 404.html

  # Necessary for search to work properly
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.highlight:
      linenums: true
      linenums_style: pymdownx.inline
  - pymdownx.inlinehilite
  - pymdownx.keys
  - attr_list
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid-experimental
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      clickable_checkbox: true
  - def_list
  - pymdownx.tabbed


 

# Can add icons throughout the ebook https://materialdesignicons.com/
#  - pymdownx.inlinehilite
  # - pymdownx.keys